services:
  - type: web
    name: iotflask
    env: python
    repo: https://github.com/Aabanekarim/iotflask
    branch: main  # Adjust if your default branch is not 'main'
    buildCommand: "pip install -r requirements.txt"
    startCommand: "flask run --host=0.0.0.0"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: development
      - key: SQLALCHEMY_DATABASE_URI
        value: "postgresql://{{DATABASE_USER}}:{{DATABASE_PASSWORD}}@{{DATABASE_HOST}}:{{DATABASE_PORT}}/{{DATABASE_NAME}}"  # Use Render's environment variables for database connection

databases:
  - name: iotflask-db
    plan: free
    region: oregon
    postgresMajorVersion: 16
    user: app_user
